<?php

namespace ContainerTN8cDBM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F2bfROJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f2bfROJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f2bfROJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'chartBuilder' => '?',
            'entityManager' => '?',
        ]);
    }
}
