controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# the "user" route name is not important yet
userhome:
    path: /user
    controller: App\Controller\UserController::homepage
    methods: "GET"
userdit:
    path: /user/edit/
    controller: App\Controller\UserController::edit
    methods: "GET"
userdb:
    path: /user/edit/
    controller: App\Controller\UserController::editdb
    methods: "POST"
userprofil:
    path: /profile/
    controller: App\Controller\UserController::profile
quizz:
    path: /quizz
    controller: App\Controller\QuizzController::displayAction
quizzId:
    path: /quizz/{id}
    controller: App\Controller\QuizzController::show
resume:
    path: /resume
    controller: App\Controller\QuizzController::resume
userHistory:
    path: /user/history
    controller: App\Controller\HistoryController::sessionHistory
charts:
    path: /charts
    controller: App\Controller\ChartsController::showCharts
chartsQuizzList:
    path: /charts/quizz
    controller: App\Controller\ChartsController::showQuizzList
chartsQuizz:
    path: /charts/quizz/{id}
    controller: App\Controller\ChartsController::showQuizzCharts